Create a mongodb-objects service and a publications endpoint
ConductionNL/OpenCatalogApp pull request #8
Opened 2024-07-01 14:51 UTC by rjzondervan

2024-07-01 15:16 UTC, WilcoLouwerse requested changes

2024-07-01 15:16 UTC, WilcoLouwerse commented on lib/Service/ObjectService.php
> +class ObjectService
Missing a class docblock

2024-07-01 15:16 UTC, WilcoLouwerse commented on lib/Service/ObjectService.php
> +	private function getClient(array $config): Client
Missing function docblockS

2024-07-01 15:16 UTC, WilcoLouwerse commented on lib/Service/ObjectService.php
> +		$object['dataSource']     = $config['mongodbCluster'];
allignment^

2024-07-01 15:16 UTC, WilcoLouwerse commented on lib/Service/ObjectService.php
> +	public function saveObject(array $data, array $config): array
Missing empty line^

2024-07-04 06:10 UTC, remko48 approved these changes

2024-07-04 06:10 UTC, merged